global.charnames = ["Oilman","Cleaverhead","Barrel","Pond","Ball","Brigade Boy","Evil Brigade Boy","Coals","Oven Mitt"];
global.chardescs = ["Big fan of oil. It's his favorite drink.","Forever doomed to spill his oil blood everywhere he goes. Leaves a trail of oil where he walks.","The sheriff of the oil rig. Can light fires with his cigarette as well as use oil.","Your friendly neighborhood pond. Spreads joy (and water).","A very standard, soggy, ball creature.","Master of the super soaker. High damage but frail.","Master of the super scalder. Same as Brigade Boy, but fire-y.","A group of mischevous coal monsters. Can hop anywhere, but leaves fire where they go. Immune to damage from fire tiles.","Tasked with cleanup duty. Dreams of being a musician someday."];
global.charabilities = [
	["Oil Slap","Does extra damage on oil spot."],
	["Oil Guzzle","Drinks oil on the ground below you."],
	["Oil Drool","Leaves a high damage oil drool pool."],
	["Oil Swipe","High damage and creates oil tiles."],
	["Split Skull","Sprays oil everywhere. No damage."],
	["Sneeze","Shoots high damage oil forward."],
	["Cigarette Toss","Creates a fire tile and deals high damage."],
	["Oil Artillery","Deals medium damage and creates an oil tile anywhere."],
	["Oil Spray","Deals low damage and creates a line of oil tiles."],
	["Bamboo Artillery","Deals low damage anywhere."],
	["Tsunami","Creates puddles in all adjacent tiles. No damage."],
	["Extinguisher","Creates a puddle anywhere. No damage."],
	["Soggy Chomp","Deals high damage and creates puddles in other tiles."],
	["Osmosis","Absorbs water it is standing on, healing if successful."],
	["Smash","Medium damage, medium range attack."],
	["Soggy Sniper","Extreme damage, but hard to aim."],
	["Water Cannon","Shoots a large low damage beam, leaving puddles behind."],
	["Splash","Medium damage, close range."],
	["Sizzling Sniper","Extreme damage, but hard to aim."],
	["Lava Cannon","Shoots a large low damage beam, leaving fire."],
	["Magma Splash","Medium damage, close range."],
	["Hop","Jump to a location and spawn fire in adjacent tiles."],
	["Flamewhistle","Spawns a row of flames and does medium damage."],
	["Ignite","When standing on a flame, absorb it and heal."],
	["Absorbtion","Clears any terrain on the spot you are standing on."],
	["Body Slam","Deals high damage. If it hits, spawn a flame."],
	["Human(?) Lighter","Spawns a flame."]
]